name: Reusable workflow example
 
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
 
jobs:
  test:
    name: Pass input my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello, ${{ inputs.username }}!
