   on: [workflow_dispatch]
   
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:    
       - uses: ansh121-private-actions-test-org/sanj-private-action-and-workflow@main
   
     call-workflow:
       uses: ansh121-private-actions-test-org/sanj-private-action-and-workflow/.github/workflows/called-workflow.yml@main
       with:
         username: Shinchan
